### ISSUE TITLE
关于日期框title颜色的问题

### ISSUE THREAD

**Issue by shenyunmeng0519** [AigeStudio/DatePicker#13]
请问能否修改title的颜色，从粉色变成其他颜色呢？
我已经试过重写DPTheme需要重写的所有方法，但是都不能修改，求教！

**Comment by AigeStudio** [comment]
DPTheme方法接受的整型值是颜色值不是资源ID

**Comment by ynhenggg** [comment]
使用了您的日历选择器，用着很好用，但是不同的应用有不同的主题色，
未找到设置DPTheme的代码，不知该怎么写，能否提供一份呢，非常感谢....

**Comment by RommelLiang** [comment]
我也在修改颜色这里纠结了一个下午，最后果断放弃了直接引用的方法，而是将项目下载到本地，将DatePicker作为Module导入项目。所有的颜色都是在cn.aigestudio.datepicker.bizs.themes下的DPBaseTheme下设置的，这个类继承自DPTheme。所以建议还是不要直接引用，手动导入的话还可以自己在对日历进行一些必要的修改和定制
