### ISSUE TITLE
我要把title的背景颜色从红色变为#256695这个颜色怎么设置 能给具体代码吗

### ISSUE THREAD

**Issue by shenyunmeng0519** [AigeStudio/DatePicker#14]

**Comment by AigeStudio** [comment]
return 0xFF256695

**Comment by shenyunmeng0519** [comment]
我按照你说的继承DPLTheme后 实现了其中的方法 但我把所有的返回值都改成0xFF256695 也不行 其他都变了 就那个最上面的title背景颜色还是红色  这是为什么？

**Comment by AigeStudio** [comment]
贴代码看看

**Comment by shenyunmeng0519** [comment]
我在我的activity中设置了这段代码 在CustomDPTheme中继承了DPTheme 然后重写了里面的方法 @Override
    public int colorTitleBG() {
        return 0xFF256695;
    }
所有方法的返回值都设置成了上面这样 但是其他都改了 就最上面的title颜色还是红色
 DPTManager.getInstance().initCalendar(new CustomDPTheme());
        DatePicker picker = (DatePicker) view.findViewById(R.id.new_act_date_picker);
        picker.setDate(2015, 7);
        picker.setMode(DPMode.SINGLE);
        picker.setOnDatePickedListener(new DatePicker.OnDatePickedListener() {
            @Override
            public void onDatePicked(String date) {
                //LogUtil.e("================",date);
                tv_start_date.setText(date);
                mPopupWindowDialog.dismiss();
                Toast.makeText(SearchMoreActivity.this, date, Toast.LENGTH_LONG).show();
            }
        });

**Comment by AigeStudio** [comment]
DPTManager.getInstance().initCalendar(new CustomDPTheme());在setContentView前调用

**Comment by shenyunmeng0519** [comment]
解决了 非常感谢
