### ISSUE TITLE
如何动态更新标志物？？

### ISSUE THREAD

**Issue by TEENSTITAN** [AigeStudio/DatePicker#17]
DPCManager.getInstance().setDecorT(listRecordFlag);

listRecordFlag 明明为空，却是上一个用户的标志

**Comment by clzd0792** [comment]
你解决了吗？README有说“必须在DatePicker显示前设置DPCManager中的相关数据”，我这边要完全退出应用进程再重启才能更新装饰物。

**Comment by TEENSTITAN** [comment]
暂没解决，装饰物和语言必须退出APP才能更新，等aige回复！！！！

**Comment by AigeStudio** [comment]
因为缓存没清除，这是个BUG，如果你import了module可以在设置标志物后直接手动清理掉缓存或写个方法清除掉缓存即可，缓存位置在DPCManager的DATE_CACHE中

**Comment by clzd0792** [comment]
问题解决了，感谢爱哥！

**Comment by AigeStudio** [comment]
不客气，这是当初设计不合理导致，没有考虑到多实例状态的问题，3.0修复

**Comment by TEENSTITAN** [comment]
在 setDecT() 之前清理掉DATE_CACHE_T 吗，我哪里错了吗  @clzd0792  贴贴你的看看

@AigeStudio  简繁体也是这样，暂时也需要清理？这个在哪呢  爱哥

**Comment by clzd0792** [comment]
我也是设置的顶部T装饰物。我在setDecorT后清除的DATE_CACHE,这样新添加的装饰物能刷新了。但是删除装饰物仍然不能刷新，后来我就在setDecorT前清除DATE_CACHE_T就可以了，这样做好不好我不知道，反正是起了作用了...另外要在DatePicker显示前设置才有用，如果一直在显示的话，invalidate一下。

**Comment by qq280948982** [comment]
呵呵哒，我也是遇到了这个问题，这点真的设计的不好。最后我的解决方案是通过JAVA反射，将DCPManager里的DATE_CACHE给清空掉，然后通过反射拿到MonthView，再调用monthView.postInvalidate()方法刷新。

**Comment by AigeStudio** [comment]
因为设计之初就没打算让它能动态改变，仅作为一个选择器调用，即将发布的新版本会解决这些问题

**Comment by TEENSTITAN** [comment]
好激动！

**Comment by JohnsonHou** [comment]
@qq280948982 能不能给我看下你的代码

**Comment by androidVHappy** [comment]
你们解决了页面刷新问题吗？     添加装饰物能刷新页面   取消装饰物的话   我这里刷新不了耶  怎么处理？大神们  谢谢

**Comment by androidVHappy** [comment]
![image](https://cloud.githubusercontent.com/assets/23274401/23702720/6d1ae000-0437-11e7-9578-69fba4ea3dc1.png)

**Comment by kangkitty** [comment]
删除装饰物更新不了，大家都怎么更新的，求教

**Comment by dukezhao** [comment]
有谁知道这样设文字为何不显示出来？
 @Override
            public void drawDecorTL(Canvas canvas, Rect rect, Paint paint) {
                paint.setColor(getResources().getColor(R.color.btn_common));
             
                canvas.drawText("xxx",0,rect.height(),paint);
            }

**Comment by renbin1990** [comment]
不需要导module,也不需要用反射,本人解决的一个办法,给大家做参考吧, 吧DatePicker,MonthView,DPCManager三个类拷贝出来放在项目里,在DPCManager的
private void setDecor(List<String> date, HashMap<String, Set<String>> cache) {
        //清除缓存数据
        DATE_CACHE.clear();
        DECOR_CACHE_BG.clear();
        DECOR_CACHE_TL.clear();
        DECOR_CACHE_T.clear();
        DECOR_CACHE_TR.clear();
        DECOR_CACHE_L.clear();
        DECOR_CACHE_R.clear();

        for (String str : date) {
            int index = str.lastIndexOf("-");
            String key = str.substring(0, index).replace("-", ":");
            Set<String> days = cache.get(key);
            if (null == days) {
                days = new HashSet<>();
            }
            days.add(str.substring(index + 1, str.length()));
            cache.put(key, days);
        }
    }
这个方法中添加几个缓存清除,DatePicker导类导拷贝出来的MonthView,自定义控件使用导出来的DatePicker,DPCManager.getInstance().setDecorBG(tmp);也使用改后的

**Comment by waterhxs** [comment]
用反射吧
try
        {
            Field dateCacheField = DPCManager.getInstance().getClass().getDeclaredField("DATE_CACHE");
            dateCacheField.setAccessible(true);
            Object dateCacheValue = dateCacheField.get("DATE_CACHE");
            HashMap<Object, Object> dateCache = (HashMap<Object, Object>)dateCacheValue;
            dateCache.clear();

            Field dateBgCacheField = DPCManager.getInstance().getClass().getDeclaredField("DECOR_CACHE_BG");
            dateBgCacheField.setAccessible(true);
            Object dateBgCacheValue = dateBgCacheField.get("DECOR_CACHE_BG");
            HashMap<Object, Object> dateBgCache = (HashMap<Object, Object>)dateBgCacheValue;
            dateBgCache.clear();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }

**Comment by waterhxs** [comment]
用反射吧
```
try
        {
            Field dateCacheField = DPCManager.getInstance().getClass().getDeclaredField("DATE_CACHE");//获得私有属性
            dateCacheField.setAccessible(true);
            Object dateCacheValue = dateCacheField.get("DATE_CACHE");
            HashMap<Object, Object> dateCache = (HashMap<Object, Object>)dateCacheValue;
            dateCache.clear();

            Field dateBgCacheField = DPCManager.getInstance().getClass().getDeclaredField("DECOR_CACHE_BG");//获得私有属性
            dateBgCacheField.setAccessible(true);
            Object dateBgCacheValue = dateBgCacheField.get("DECOR_CACHE_BG");
            HashMap<Object, Object> dateBgCache = (HashMap<Object, Object>)dateBgCacheValue;
            dateBgCache.clear();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
```
