### ISSUE TITLE
首先感谢您提供这么优质的代码，然后想请教下，如何跳转到指定的日期呢？

### ISSUE THREAD

**Issue by Haofengshang** [AigeStudio/DatePicker#24]
我是这么写的，`Toast.makeText(mActivity, "跳转到2016-8", Toast.LENGTH_LONG).show();
        this.setDate(2016, 8);
        this.setMode(DPMode.SINGLE);`

第一次点击跳转的按钮可以执行，然后左右随便滑动一下，日历就刷新不了了，只会更新头部的年月。有没有一个刷新的方法？希望能得到您的解答。非常感谢！

**Comment by max8888888** [comment]
同问，等爱哥解答~

**Comment by AigeStudio** [comment]
https://github.com/AigeStudio/DatePicker/issues/17

**Comment by rw15250** [comment]
同问，第二次界面就白了

**Comment by rw15250** [comment]
void setDate1(int year, int month) {
        centerYear = year;
        centerMonth = month;
        indexYear = 0;
        indexMonth = 0;
        buildRegion();
        computeDate();
        requestLayout();
        invalidate();

        smoothScrollTo(0, 0);
        lastMoveY =0;
    }
这样就ok了
