### ISSUE TITLE
今天日期标识问题

### ISSUE THREAD

**Issue by ixnyu** [AigeStudio/DatePicker#28]
按把系统时间改了后 只有杀掉应用程序 才能获取到改过后的日期 有没有方法传递一个 年月日来自己设定今天日期标识或者取消今天标识
setDPDecor 这个方法设置的背景标识会和今天的标识重叠形成一个新颜色

**Comment by ixnyu** [comment]
看了其他的issues 找到了办法 清除缓存即可

**Comment by JohnsonHou** [comment]
@ixnyu 能否指导一下如何清除缓存
